apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-uploads
  labels:
    app.kubernetes.io/name: gestion-produits
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
